### ISSUE TITLE
Webchimera and ChromeCast

### ISSUE THREAD

**Issue by nilparra** [jaruba/WebChimeraPlayer#10]
Do you know when Webchimera can be compatible with ChromeCast for sending video on TV ?

Sorry for my english.

Regards

**Comment by jaruba** [comment]
How do you use WebChimera? In Node-Webkit (NW.js) or in the browser?

**Comment by jaruba** [comment]
I'm expecting you to use it in NW.js. The best place for a chromecast feature is in [peerflix](https://github.com/mafintosh/peerflix) (there is already a [request made about it](https://github.com/mafintosh/peerflix/issues/111))

There are also many options to implement chromecast support in a node.js app directly:
- [peercast](https://github.com/mafintosh/peercast) (torrent-stream + chromecast)
- [castnow](https://github.com/xat/castnow)
- [chromecast-js](https://github.com/guerrerocarlos/chromecast-js) (this is apparently what Popcorn Time uses)

I don't think this functionality should be added in the player itself, it should be done from JavaScript. 

But if you want to start streaming to chromecast by just clicking a button in the player, then you can use onen of the libraries I linked above to create a chromecast feature to your app, then read [this article](http://wiki.webchimera.org/Adding_a_Custom_Button_in_the_Toolbar) about Creating a Custom Button in the Toolbar that triggers a JavaScript function (which should initiate the chromecast implementation).

So you can already do all this now, all the needed libraries and required docs are out there, but it should be implemented in the app, not the player. :)
