### ISSUE TITLE
TitleBars not displaying when the MRL doesn't work

### ISSUE THREAD

**Issue by fapeci** [jaruba/WebChimeraPlayer#3]
Hi

I am loading several instances on multiscreen on chimera player but the instances where there is a problem with streaming or mrl is not working it does not show the custom title. I need this to identify the problematic streams

**Comment by jaruba** [comment]
I've removed your comment from WebChimera Q&A as it was off topic for that particular question.

Did you by any chance check if the error from your MRL's trigger the ```.MediaPlayerEncounteredError``` event?

This should normally be done by using [.catchEvent()](http://wiki.webchimera.org/.catchEvent()), in your case, see if this works in JS to record the MRL with errors in the browser console log:

    function handleError() {
        console.log("error found for mrl: " + wjs("#webchimera").plugin.playlist.items[wjs("#webchimera").plugin.playlist.currentItem].mrl );
        return;
    }
 
    wjs("#webchimera").catchEvent("MediaPlayerEncounteredError", handleError);

*This code presumes that the plugin object has the ID: "webchimera"*

**Comment by jaruba** [comment]
If that doesn't work to catch the correct MRL (it might not work if the playlist changes position instantly after sending that event).

Then you will have to modify WebChimera Player internally. So you will need to go to ```\player\themes\sleek\TitleBar.qml``` then change this line:

    visible: (vlcPlayer.state == 3 || vlcPlayer.state == 4 || vlcPlayer.state == 6) ? fullscreen ? true : false : false

to this:

    visible: true

to make the title bar always visible, no matter the circumstance. If that still does not fill your requirements. Then you should also change these lines (there are 2 lines in this file with that are like this, both should be changed):

    opacity: vlcPlayer.time == 0 ? 0 : fullscreen ? settings.ismoving > 5 ? 0 : 0.7 : 0.7

to this:

    opacity: 1

to also remove the opacity effect.

*I cannot add these changes to the next version as this should not be the normal behavior for the player.*

**Comment by jaruba** [comment]
You should also change this line:

    opacity: vlcPlayer.time == 0 ? 0 : fullscreen ? settings.ismoving > 5 ? 0 : 0.7 : 0.7

to this:

    opacity: 0.7

For the black background of the text to remain too.

**!** Keep in mind that these changes will keep the title bar active even when the mouse is inactive in fullscreen. If you want to keep this particular functionality in the player, then you will have to change these lines to ```opacity: settings.ismoving > 5 ? 0 : 1``` and respectively ```opacity: settings.ismoving > 5 ? 0 : 0.7``` instead of those I mentioned above.

**Comment by fapeci** [comment]
Unfortunately doesn't work. It shows Black player only the buttons to play
and nothing else.

**Comment by jaruba** [comment]
This doesn't mean it didn't work, the title bar might be there, but the MRL might not be set as the title because of the error that stopped the process from completing.

You could always use the shortcut: "CTRL + L" to view the playlist, even if the button isn't available. In the playlist you should be able to see the title of the current video item.

**Comment by fapeci** [comment]
Thanks that worked

**Comment by fapeci** [comment]
Can we make the togglePlaylist() to be run automatically for MRLs that do not play or open, so that I can see the Channel Name

**Comment by jaruba** [comment]
It depends. Only if the error triggers the "MediaPlayerEncounteredError" event, you will need to check if it triggers it as I explained here:
https://github.com/jaruba/WebChimeraPlayer/issues/3#issuecomment-77925676

Otherwise, we don't know when it doesn't work to trigger ```togglePlaylist()```.

**Comment by jaruba** [comment]
Or you could try implementing it directly to see if it triggers, by opening ```/player/themes/sleek/main.qml``` and adding these lines:

	Connections {
		 target: vlcPlayer
		 onMediaPlayerEncounteredError: {
			wjs.togglePlaylist();
		}
	}

right before the last ```}``` in the file.

**Comment by fapeci** [comment]
Good news, it catches the onMediaPlayerEncounteredError event when the MRL is not loading (I can see that on the browser console) but unfortunately it doesn't toggle the Playlist, don't know why. I have tried even to put the togglePlaylist() just after the goBig() function but still doesn't work.

**Comment by jaruba** [comment]
*after the goBig() function*

Every time I see that function name it makes me laugh.. but couldn't think of a more suitable name for it..

The position of the ```.togglePlaylist()``` function shouldn't matter at all. Could you check what the log in [DebugView](https://technet.microsoft.com/en-us/library/bb896647.aspx) says? (ignore all the non-notifyable errors, they mean nothing)

Maybe there's something there that will tell us why it didn't work.

**Comment by jaruba** [comment]
Or instead of the code I recommended earlier, you can try to do this directly in ```/core/Functions.qml```, by adding:

    vlcPlayer.onMediaPlayerEncounteredError.connect( togglePlaylist );

inside the ```onQmlLoaded()``` function. :)

**Comment by fapeci** [comment]
Seems togglePlaylist(); function is not triggered at all unless pressing CTRL+L when you are on fullscreen mode, still haven't got the clue why

**Comment by jaruba** [comment]
CTRL+L only does ```wjs.togglePlaylist()```, I think the playlist is triggered, but can only be viewed in fullscreen because multiscreen mode stops it from showing in minimized mode. Let me check the code a bit.

**Comment by jaruba** [comment]
I checked, multiscreen isn't stopping ```.togglePlaylist()``` from showing, so the only logical conclusion is that ```MediaPlayerEncounteredError``` isn't triggering.

But there should be no reason for it not to trigger in QML and trigger in JS. To check if it only triggers in JavaScript, we'd have to use the first example again and change it a bit. Try this in JS:

    function handleError() {
        wjs("#webchimera").plugin.emitJsMessage("[toggle-playlist]");
        return;
    }

    wjs("#webchimera").catchEvent("MediaPlayerEncounteredError", handleError);

Then add this line to ```/core/Functions.qml```:

    if (message == "[toggle-playlist]") togglePlaylist();

in the ```onMessage()``` function after this line:

    if (startsWith(message,"[opening-text]")) { settings.openingText = message.replace("[opening-text]",""); settings = settings; } // Get New Opening Text

This will make the On Page JS request a ```togglePlaylist()``` from the Player when the "MediaPlayerEncounteredError" event is triggered.

**Comment by jaruba** [comment]
did that work for you?

**Comment by fapeci** [comment]
Partially, somehow the Playlist is toggled for all multiscreen elements even if other MRLs are working fine (I have made a single MRL out of 4 MRL to be not working). Below the screenshot for 4 elements in multiscreen:
http://pasteboard.co/1JnGGh34.jpg

**Comment by jaruba** [comment]
You assigned a different id to each multiscreen player? And attached the event handler to each element? If so, then this is now a problem with the Plugin or libVlc for triggering "MediaPlayerEncounteredError" when there is no error.

**Comment by fapeci** [comment]
From the browser I could see a single error only for the wrong MRL. I guess
as soon as the playlist is toggled it stays that way.

**Comment by jaruba** [comment]
Can you paste your code for how you declare the players with ```.addPlayer()``` then how you attach the handlers to ```MediaPlayerEncounteredError```? There could also be some error in the code.

**Comment by fapeci** [comment]
`<!DOCTYPE html>
<html>

<head>

<link rel="icon" href="http://www.webchimera.org/favicon.ico">
<meta charset="UTF-8">
<link href="css/styles.css" rel="stylesheet" type="text/css">

<title>Multiscreen Demo - WebChimera Player</title>

</head>

<body>

<div id="close_wrapper"><a id="close_button" href="index.html"><img src="images/close_but.png"></a></div>

<div id="page_title"><h1>Multiscreen Demo</h1><span id="page_desc"><br>Click on a Video!</span></div>


<div id="player_wrapper" style="background-color: #000">
<div style="width: 100%; height: 100%; background: #00FFFF">
<div style="position: absolute;z-index: 10; background-color: rgba(0, 0, 0, 1); left: 5px; top: 5px; width: 150px; height: 20px; display: block;">This text is visible</div>
<div id="wrapper1" style="position: relative;z-index: 1;display: inline-block; width: 49%; height: 49%; margin-left: 5px; margin-top: 2px; text-align: top;"></div>
<div style="position: absolute;z-index: 10; background-color: rgba(0, 0, 0, 1); left: 500px; top: 5px; width: 150px; height: 20px; display: block;">This text is visible</div>
<div id="wrapper2" style="display: inline-block; width: 49%; height: 49%; margin-top: 2px"></div>
<div id="wrapper3" style="display: inline-block; width: 49%; height: 49%; margin-left: 5px"></div>
<div id="wrapper4" style="display: inline-block; width: 49%; height: 49%;"></div>
</div>
</div>

<script src="player/webchimera.js" type="text/javascript"></script>
<script>

// create players with Multiscreen enabled
wjs("#wrapper1").addPlayer({ id: "webchimera1", theme: "sleek", multiscreen: 1, autoplay: 1, titleBar: "both" });
wjs("#wrapper2").addPlayer({ id: "webchimera2", theme: "sleek", multiscreen: 1, autoplay: 1, titleBar: "both" });
wjs("#wrapper3").addPlayer({ id: "webchimera3", theme: "sleek", multiscreen: 1, autoplay: 1 });
wjs("#wrapper4").addPlayer({ id: "webchimera4", theme: "sleek", multiscreen: 1, autoplay: 1 });


//wjs("#webchimera1").catchEvent("MediaPlayerEncounteredError", handleError);
// add the playlist items to the players
wjs("#webchimera1").addPlaylist({url: "http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/cnbc_eu/ls_satlink/b_,264,528,828,.m3u8", title: "Sport News"});
wjs("#webchimera2").addPlaylist({url: "http://wpc.c1a9.1edgecastcdn.net/hls-live/20C1A9/cnbc_eu/ls_satlink/b_,264,528,828,.m3u8", title: "Sport News"});
//wjs("#webchimera3").addPlaylist("http://www.youtube.com/watch?v=RSY75mIIpB0");
//wjs("#webchimera4").addPlaylist("http://www.youtube.com/watch?v=b-_53i63DfY");
wjs("#webchimera3").addPlaylist({url: "http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/cnbc_eu/ls_satlink/b_,264,528,828,.m3u8", title: "Sport News"});
wjs("#webchimera4").addPlaylist({url: "http://wpc.c1a9.edgecastcdn.net/hls-live/20C1A9/cnbc_eu/ls_satlink/b_,264,528,828,.m3u8", title: "Sport News"});

function handleError() {
    wjs("#webchimera1").plugin.emitJsMessage("[toggle-playlist]");
	wjs("#webchimera2").plugin.emitJsMessage("[toggle-playlist]");
	wjs("#webchimera3").plugin.emitJsMessage("[toggle-playlist]");
	wjs("#webchimera4").plugin.emitJsMessage("[toggle-playlist]");
	 
    return;
}

wjs("#webchimera1").catchEvent("MediaPlayerEncounteredError", handleError);
wjs("#webchimera2").catchEvent("MediaPlayerEncounteredError", handleError);
wjs("#webchimera3").catchEvent("MediaPlayerEncounteredError", handleError);
wjs("#webchimera4").catchEvent("MediaPlayerEncounteredError", handleError);

</script>

</body>

</html>
>
`

And the following is the screenshot of browser log http://pbrd.co/1FNEYrQ

**Comment by jaruba** [comment]
This is your problem right here:

	function handleError() {
		wjs("#webchimera1").plugin.emitJsMessage("[toggle-playlist]");
		wjs("#webchimera2").plugin.emitJsMessage("[toggle-playlist]");
		wjs("#webchimera3").plugin.emitJsMessage("[toggle-playlist]");
		wjs("#webchimera4").plugin.emitJsMessage("[toggle-playlist]");
		return;
	}

	wjs("#webchimera1").catchEvent("MediaPlayerEncounteredError", handleError);
	wjs("#webchimera2").catchEvent("MediaPlayerEncounteredError", handleError);
	wjs("#webchimera3").catchEvent("MediaPlayerEncounteredError", handleError);
	wjs("#webchimera4").catchEvent("MediaPlayerEncounteredError", handleError);

It should be:

	function handleError1() {
		wjs("#webchimera1").plugin.emitJsMessage("[toggle-playlist]");
		return;
	}
	function handleError2() {
		wjs("#webchimera2").plugin.emitJsMessage("[toggle-playlist]");
		return;
	}
	function handleError3() {
		wjs("#webchimera3").plugin.emitJsMessage("[toggle-playlist]");
		return;
	}
	function handleError4() {
		wjs("#webchimera4").plugin.emitJsMessage("[toggle-playlist]");
		return;
	}


	wjs("#webchimera1").catchEvent("MediaPlayerEncounteredError", handleError1);
	wjs("#webchimera2").catchEvent("MediaPlayerEncounteredError", handleError2);
	wjs("#webchimera3").catchEvent("MediaPlayerEncounteredError", handleError3);
	wjs("#webchimera4").catchEvent("MediaPlayerEncounteredError", handleError4);

**Comment by fapeci** [comment]
Flawless

**Comment by jaruba** [comment]
Great! :)
