### ISSUE TITLE
nw12

### ISSUE THREAD

**Issue by smolleyes** [jaruba/WebChimeraPlayer#4]
hello jaruba

you have webchimera ok in nw 12 ?

navigator.plugins array length is always 0 for me Oo

**Comment by jaruba** [comment]
you mean nw 0.12.0? yeah, works great for me

**Comment by smolleyes** [comment]
damn strange 

why peoples tell me that ?

https://github.com/nwjs/nw.js/issues/3195

can show your package.json ?

**Comment by smolleyes** [comment]
i just builded wc on my ubuntu and updated the player too

webkit plugin true in package.json and sill no plugins at all :(

**Comment by smolleyes** [comment]
i'm here

https://gitter.im/RSATom/WebChimera

**Comment by jaruba** [comment]
Oh, I didn't test it on Linux.. if they say it doesn't work, then you'll probably have to downgrade to a nw that works with NPAPI's

**Comment by smolleyes** [comment]
downloading custom build nw 11.5 of popcorn time i ll try

**Comment by jaruba** [comment]
It might not be necessary, as @mscreenie mentioned on your post: nwjs/nw.js#3195

By following the link to http://blog.chromium.org/2014/11/the-final-countdown-for-npapi.html

The author of the article wrote:
*We will provide an override for advanced users (via chrome://flags/#enable-npapi) and enterprises (via Enterprise Policy) to temporarily re-enable NPAPI while they wait for mission-critical plugins to make the transition.*

Then checking for chromium accepted arguments.. we land on this page:
http://peter.sh/experiments/chromium-command-line-switches/

Than mentiones:
--enable-npapi - Enables the use of NPAPI plugins.

:)

**Comment by smolleyes** [comment]
even with nw 0.11.5 wich is chromium 38 i have no plugins listed :/ strange

**Comment by jaruba** [comment]
ofc it doesn't they did say it doesn't work from chromium 35+

did you try to add ``--enable-npapi`` in "chromium-args" and it didn't work?

**Comment by smolleyes** [comment]
yup not working, boring  :/

**Comment by jaruba** [comment]
strange indeed, I'll have to test this myself but can't in the next week as I will be away from my PC and installing a Linux VM on my laptop is counter productive (as it will take a lot longer to install/test then on the PC)

How did you add two arguments to "chromium-args" in the manifest? Because I can't seem to find any official documentation on doing so.

(by two I mean "--load-plugin" and "--enable-npapi")

**Comment by smolleyes** [comment]
i tried --enable-npapi alone

downloading 0.9.2 now to try

**Comment by jaruba** [comment]
btw, I tested nw 0.12.0 with both Windows and Mac, and WebChimera worked. Seems to be only a Linux issue.

**Comment by smolleyes** [comment]
damn no there s another problem not psosible

navigator.plugins
PluginArray {length: 0, item: function, namedItem: function, refresh: function}

Object {http_parser: "1.0", node: "0.11.9", v8: "3.22.24", uv: "0.11.15", zlib: "1.2.5"…}
chromium: "32.0.1700.107"

with nw 0.9.2 / chromium 32

Oo

**Comment by smolleyes** [comment]
humm no it s ok in nw 0.9.2 :/

**Comment by smolleyes** [comment]
args doc

if you want to add multiple arguments, separate each two arguments by space. This field can take a number of flags in one argument as well, via enclosing them in single quotation marks.

**Comment by smolleyes** [comment]
i thinl webchimera will have to switch to ppapi now :p

**Comment by jaruba** [comment]
We talked about ppapi and it's not possible to port webchimera to ppapi atm, as there is no qt quick 2 for ppapi, and that is a major part of the plugin.

**Comment by smolleyes** [comment]
that s a big problem this plugin will not be usable in chrome linux... forced to use firefox and or old node-webkit :/

**Comment by jaruba** [comment]
Rome wasn't built in a day. Just have to be patient, solutions will appear in time. :)

**Comment by smolleyes** [comment]
sure :)

i ll retry to build nw with custom codecs :p

**Comment by jaruba** [comment]
Are you sure that nw 0.9.2 - linux (chromium 32) is the latest that the plugin works on? I'm thinking of probably making some prepackaged nw demos with webchimera (with frozen versions of nw) to better handle the changes with npapi deprecation.
