### ISSUE TITLE
Hide titleBar when not in fullscreen mode

### ISSUE THREAD

**Issue by kevkha** [jaruba/WebChimeraPlayer#7]
I attempt to create a new theme based on sleek and set titleBar to "both" in UIsettings.qml. titleBar shows but does not hide like in fullscreen mode. How do I make it happen? Thanks.

**Comment by jaruba** [comment]
Player API doesn't have anything parameter for this as it was never needed for Web use. Node-webkit is very different though.

Myself, as in a previous NW project I was also annoyed by the title bar when not in fullscreen.. I chose to take a different approach and use titleBar on "fullscreen" only, and when not in fullscreen, I just set ``win.title`` to the appropriate video title. (as this changes the window name to the video name)

A sample code would be:

    win = gui.Window.get();
    win.title = [my-video-title]:

Ofc, this can only be done if you also know the title of the video in JavaScript.

Does this suite your needs? If not, what kind of video sources do you use?

Would you prefer a solution to hide the title bar like in fullscreen (when it is not fullscreen) or would you prefer a solution to get the video title in JavaScript to set the window's title? (which I think looks better and cleaner in NW)

**Comment by kevkha** [comment]
Hi jaruba, I don't need NW win.title. I prefer to have a titleBar rectangle to show when mouse over and auto hide like in fullscreen. I will utilize this rectangle to display some other elements from back end server and probably add a key event to trigger it as well along side with mouse event. Thanks.

**Comment by jaruba** [comment]
Try going to ``/player/themes/sleek/components/TitleBar.qml`` and changing:

	opacity: vlcPlayer.Playing === false && vlcPlayer.Paused === false && vlcPlayer.Buffering === false ? 0 : fullscreen ? settings.ismoving > 5 ? 0 : 0.7 : 0.7

to:

	opacity: vlcPlayer.Playing === false && vlcPlayer.Paused === false && vlcPlayer.Buffering === false ? 0 : fullscreen ? settings.ismoving > 5 ? 0 : 0.7 : settings.ismoving > 5 ? 0 : 0.7

and also change:

	opacity: vlcPlayer.Playing === false && vlcPlayer.Paused === false && vlcPlayer.Buffering === false? 0 : fullscreen ? settings.ismoving > 5 ? 0 : 1 : 1

to this:

	opacity: vlcPlayer.Playing === false && vlcPlayer.Paused === false && vlcPlayer.Buffering === false? 0 : fullscreen ? settings.ismoving > 5 ? 0 : 1 : settings.ismoving > 5 ? 0 : 1

Tell me if that worked for you. :)

**Comment by kevkha** [comment]
Very nice! It works like a champ. Thank you.

**Comment by jaruba** [comment]
Great! Glad to hear it. :)
