### ISSUE TITLE
Loading Resource on empty playlist

### ISSUE THREAD

**Issue by kevkha** [jaruba/WebChimeraPlayer#8]
When I start the player without .addPlaylist() I always get "Loading Resource" and the animated images. Is it possible to not showing this message when playlist is empty?

**Comment by jaruba** [comment]
Try opening ``/player/themes/sleek/themes/SplashScreen.qml`` and change the 13th line from this:

    visible: vlcPlayer.state < 3 ? true : false

to this:

    visible: vlcPlayer.state < 3 && vlcPlayer.state > 0 ? true : false

**Comment by kevkha** [comment]
That worked! Correct path is <code>/player/themes/sleek/components/SplashScreen.qml</code>  Thanks mate!

**Comment by jaruba** [comment]
srry about the path. glad it worked :)
