### ISSUE TITLE
Plug-in size

### ISSUE THREAD

**Issue by Ivshti** [jaruba/WebChimeraPlayer#9]
Hello,

I know Qt takes up most of the size of the plugin, but it's a framework with a ton of features and only a handful are utilized by WebChimera. Is there a way to build it with less features so that the size of WebChimera is reduced?

Thank you

**Comment by jaruba** [comment]
I'm a bit unsure of what you are saying. The plugin and the player are two different things (as [explained here](http://wiki.webchimera.org/Introduction)).

So are you saying that the plugin (the part of WebChimera that you install locally) is to large?

Or that WebChimera Player (the ``/player`` folder) that is hosted on your site/app is to large?

**Comment by Ivshti** [comment]
I mean the WebChimera browser plugin. After the small research I did, I figured most of the space was taken by the VLC plugins, which is totally fine.

The issue is that we're shipping a NW.js app, and we don't want to increase our bundle size by 20MB.

However, it seems that we don't need most of the VLC plug-ins, which will decrease the size by 60%

**Comment by jaruba** [comment]
Well, if you are using WebChimera Player too in your app, then you should also probably minify all ``.js`` and ``.qml`` files. (this should significantly reduce it's size)

As of WebChimera Plugin, you should be able to remove most of the files you don't need and it shouldn't be a problem. (can't be sure though)

In the ``/lua`` folders are the vlc plugins used. I can spot some ``.luac`` files that are just used to decode links in the ``/lua/playlist`` that you might not need.

You can check the ``/qml`` folder too, if your not using WebChimera Player and also not use ``QtGraphicalEffects`` you might be able to remove that too.

But if you ask this on WebChimera Plugin's issue page I'm sure @RSATom can offer a lot more insight into this issue then I can, maybe even help you with building the plugin yourselves, in which case you could probably make it a lot smaller.
